### PR TITLE
Enable use of NEST 3

### PR DESCRIPTION
**Pull request by jarsi**
With the upcoming release of NEST 3 some function calls change a little bit. This PR addresses these changes and guarantees compatibility with both NEST 2 and NEST 3. At the beginning of a simulation it is determined whether NEST 2 or 3 features should be used. Based on this the parts in question are run accordingly.

### CODE REVIEW

**Comment by AlexVanMeegen** [comment]
Great work, @jarsi! :fire: Apologies for letting this hang in the air for so long. Not sure though if I am an appropriate reviewer, my NEST 3 is not yet fluent. @jasperalbers, do you have time to take a look? Or maybe @ackurth?

**Review by jasperalbers — CHANGES_REQUESTED** [review]
Looks really good! I formulated my suggested changes as a PR onto this one, see [here](https://github.com/jarsi/multi-area-model/pull/4).

**Review by jasperalbers — APPROVED** [review]
👍🏼

**Comment by jarsi** [comment]
Thanks @jasperalbers for your review! I went ahead and merged with master

**Pull request merged**
